### PR TITLE
Localization / Text Domain

### PR DESCRIPTION
**Pull request by scottbasgaard**
@TheWrongAlice should use load_plugin_textdomain and a unique text domain when using __() and _e().

- https://codex.wordpress.org/Function_Reference/load_plugin_textdomain

Noticed you are using the correct functions for outputting strings but 'example' for text domains.

Could use 'sobazaar-wordpress'.

Let me know if you have any questions here!

### CODE REVIEW

**Comment by scottbasgaard** [comment]
@TheWrongAlice can you take a look at this PR and merge?

Cleaned up some stuff based on coding standards, added localization and some needed escaping.

Can you show me an example board I can test?

Also, will you update the SOBAZAAR_EMBED_SRV for production?

**Comment by TheWrongAlice** [comment]
I checked out your PR... Looks good, except... I expected a language file to be added? .mo / .po ?

**Comment by scottbasgaard** [comment]
@TheWrongAlice can add it, not needed though on our end as we can do this outside the plugin.

**Comment by TheWrongAlice** [comment]
But the wordpress standards do call for it right? We are hoping to use this plugin in more contexts eventually

**Comment by scottbasgaard** [comment]
Not a requirement, I can add though :+1:

**Comment by scottbasgaard** [comment]
@TheWrongAlice added.

**Pull request merged**
